model:
    name: two_view_pipeline
    extractor:
        name: extractors.ripepp
        inference_conf:
          threshold: 0.5
          top_k: 2048
          nms_size: 3
          subpixel_sampling: true
        variant: default
    matcher:
      name: matchers.lightglue_trained
      weights: null  # null -> auto-resolve/download the default checkpoint; or set a path/variant
      depth_confidence: -1
      width_confidence: -1
      filter_threshold: 0.1
benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 1200
      eval:
        estimator: poselib
        ransac_th: 0.5
    hpatches:
      eval:
        estimator: poselib
        ransac_th: 0.5
      model:
        extractor:
          inference_conf: # overwrite config above
            topper: 1024
